language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-25
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-25 # google play services
    - sys-img-armeabi-v7a-addon-google_apis-google-25
    
licenses: 
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-c81a61d9
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install: 
  - "chmod +x gradlew"

