language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-25
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-25 # google play services
    - sys-img-armeabi-v7a-addon-google_apis-google-25
    

before_script:
  # Wait for emulator fully-booted and disable animations
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - sleep 30
  - adb shell input keyevent 82 &
licenses: 
    - android-sdk-preview-license-.+
    - android-sdk-license-c81a61d9
    - android-sdk-license-.+
    - google-gdk-license-.+
    - '.+'

before_install: 
  - "chmod +x gradlew"
  
 script:
  - ./gradlew clean assembleDebug -x library:signArchives -PdisablePreDex

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
